=== cespedesz07/ActivitiesGeneratorBE/tagged_texts/textO.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT corpus (encabezado, contenido)>

<!ATTLIST corpus
    id_doc     ID        #REQUIRED
>


<!ELEMENT encabezado (titulo_doc, autor, fuente, fecha, nivel)>

<!ELEMENT titulo_doc (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT fuente (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT nivel (#PCDATA)>


<!ELEMENT contenido (sentence+)>
<!ELEMENT sentence (token+)>
<!ELEMENT token  (#PCDATA) >
<!ATTLIST sentence
    id  CDATA  #REQUIRED
    
>

<!ATTLIST token
    id              CDATA  #REQUIRED
    lemma           CDATA  #REQUIRED   
    form            CDATA  #REQUIRED
    tag             (PRPos|WPos|JJ|JJR|I|JJS|POS|RB|RBR|RBS|WRB|CC|DT|WDT|PDT|UH|NNS|NN|NNP|NP00000|NP|NP00G00|NP00O00|NP00V00|NP00SP0|NNPS|RP|TO|IN|EX|WP|PRP|Fd|Fc|Flt|Fla|Fs|Fat|Faa|Fg|Fz|Fpt|Fpa|Ft|Fp|Fit|Fia|Fe|Frc|Fra|Fx|Fh|Fct|Fca|MD|VBG|VB|VBN|VBD|VBP|VBZ|W|Z|Zp|Zm|Zu)  #REQUIRED
    ctag            (PRPos|WPos|JJ|JJR|I|JJS|POS|RB|RBR|RBS|WRB|CC|DT|WDT|PDT|UH|NNS|NN|NNP|NP00000|NP|NP00G00|NP00O00|NP00V00|NP00SP0|NNPS|RP|TO|IN|EX|WP|PRP|Fd|Fc|Flt|Fla|Fs|Fat|Faa|Fg|Fz|Fpt|Fpa|Ft|Fp|Fit|Fia|Fe|Frc|Fra|Fx|Fh|Fct|Fca|MD|VBG|VB|VBN|VBD|VBP|VBZ|W|Z|Zp|Zm|Zu)  #REQUIRED      
    pos             (adjective|adposition|adverb|conjunction|date|determiner|interjection|noun|number|particle|preposition|pronoun|punctuation|verb)  #REQUIRED
    type            (currency|unit|possessive|general|interrogative|coordinating|predeterminer|common|proper|to|personal|colon|comma|curlybracket|etc|exclamationmark|hyphen|other|parenthesis|percentage|period|questionmark|quotation|semicolon|slash|squarebracket|modal)  #IMPLIED
    num             (plural|singular)  #IMPLIED
    vform           (gerund|infinitive|participle|past|personal)  #IMPLIED
    punctenclose    (open|close)  #IMPLIED
    person          (3)  #IMPLIED
    degree          (comparative|superlative) #IMPLIED
    neclass         (location|organization|other|person) #IMPLIED
>

=== cespedesz07/ActivitiesGeneratorBE/tagged_texts/C1/t1C1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE corpus SYSTEM "textO.dtd">
<corpus id_doc="t1C1">
  <encabezado>
    <titulo_doc>Philosophy</titulo_doc>
    <autor>Julie Bray</autor>
    <fuente>"https://learnenglish.britishcouncil.org/en/magazine/philosophy"</fuente>
    <fecha>Marzo 2018</fecha>
    <nivel>C1-CECR</nivel>
  </encabezado>
  <contenido>
    <sentence id="1">
      <token id="t1.1" form="﻿" lemma="﻿" tag="Fz" ctag="Fz" pos="punctuation" type="other"> </token>
      <token id="t1.2" form="Philosophy" lemma="philosophy" tag="NP" ctag="NP" pos="noun"
        type="proper"> </token>
      <token id="t1.3" form="." lemma="." tag="Fp" ctag="Fp" pos="punctuation" type="period"
      > </token>
    </sentence>
    <sentence id="2">
      <token id="t2.1" form="By" lemma="by" tag="IN" ctag="IN" pos="preposition"> </token>
      <token id="t2.2" form="Julie_Bray" lemma="julie_bray" tag="NP" ctag="NP" pos="noun"
        type="proper"> </token>
      <token id="t2.3" form="." lemma="." tag="Fp" ctag="Fp" pos="punctuation" type="period"
      > </token>
    </sentence>
    <sentence id="3">
      <token id="t3.1" form="“" lemma="“" tag="Fra" ctag="Fra" pos="punctuation" type="quotation"
        punctenclose="open"> </token>
      <token id="t3.2" form="We" lemma="we" tag="PRP" ctag="PRP" pos="pronoun" type="personal"> </token>
      <token id="t3.3" form="are" lemma="be" tag="VBP" ctag="VBP" pos="verb" vform="personal"> </token>
      <token id="t3.4" form="such" lemma="such" tag="DT" ctag="DT" pos="determiner"> </token>
      <token id="t3.5" form="stuff" lemma="stuff" tag="NN" ctag="NN" pos="noun" type="common"
        num="singular"> </token>
      <token id="t3.6" form="as" lemma="as" tag="IN" ctag="IN" pos="preposition"> </token>
      <token id="t3.7" form="dreams" lemma="dream" tag="NNS" ctag="NNS" pos="noun" type="common"
        num="plural"> </token>
      <token id="t3.8" form="are" lemma="be" tag="VBP" ctag="VBP" pos="verb" vform="personal"> </token>
      <token id="t3.9" form="made" lemma="make" tag="VBN" ctag="VBN" pos="verb" vform="participle"> </token>
      <token id="t3.10" form="on" lemma="on" tag="IN" ctag="IN" pos="preposition"> </token>
      <token id="t3.11" form="and" lemma="and" tag="CC" ctag="CC" pos="conjunction"
        type="coordinating"> </token>
      <token id="t3.12" form="our" lemma="our" tag="PRPos" ctag="PRPos" pos="pronoun"
        type="possessive"> </token>
      <token id="t3.13" form="little" lemma="little" tag="JJ" ctag="JJ" pos="adjective"> </token>
      <token id="t3.14" form="life" lemma="life" tag="NN" ctag="NN" pos="noun" type="common"
        num="singular"> </token>
      <token id="t3.15" form="is" lemma="be" tag="VBZ" ctag="VBZ" pos="verb" vform="personal"
        person="3"> </token>
      <token id="t3.16" form="rounded" lemma="round" tag="VBN" ctag="VBN" pos="verb"
        vform="participle"> </token>
      <token id="t3.17" form="with" lemma="with" tag="IN" ctag="IN" pos="preposition"> </token>
      <token id="t3.18" form="a" lemma="a" tag="DT" ctag="DT" pos="determiner"> </token>
      <token id="t3.19" form="sleep" lemma="sleep" tag="NN" ctag="NN" pos="noun" type="common"
        num="singular"> </token>
      <token id="t3.20" form="." lemma="." tag="Fp" ctag="Fp" pos="punctuation" type="period"> </token>
      <token id="t3.21" form="”" lemma="”" tag="Frc" ctag="Frc" pos="punctuation" type="quotation"
        punctenclose="close"> </token>
      <token id="t3.22" form="(" lemma="(" tag="Fpa" ctag="Fpa" pos="punctuation" type="parenthesis"
        punctenclose="open"> </token>
      <token id="t3.23" form="Shakespeare" lemma="shakespeare" tag="NP" ctag="NP" pos="noun"
        type="proper"> </token>
      <token id="t3.24" form=")" lemma=")" tag="Fpt" ctag="Fpt" pos="punctuation" type="parenthesis"
        punctenclose="close"> </token>
      <token id="t3.25" form="." lemma="." tag="Fp" ctag="Fp" pos="punctuation" type="period"
      > </token>
    </sentence>
    <sentence id="4">
      <token id="t4.1" form="Does" lemma="do" tag="VBZ" ctag="VBZ" pos="verb" vform="personal"
        person="3"> </token>
      <token id="t4.2" form="this" lemma="this" tag="DT" ctag="DT" pos="determiner"> </token>
      <token id="t4.3" form="sentence" lemma="sentence" tag="NN" ctag="NN" pos="noun" type="common"
        num="singular"> </token>
      <token id="t4.4" form="make" lemma="make" tag="VB" ctag="VB" pos="verb" vform="infinitive"> </token>
      <token id="t4.5" form="you" lemma="you" tag="PRP" ctag="PRP" pos="pronoun" type="personal"> </token>
      <token id="t4.6" form="think" lemma="think" tag="VB" ctag="VB" pos="verb" vform="infinitive"> </token>
      <token id="t4.7" form="?" lemma="?" tag="Fit" ctag="Fit" pos="punctuation" type="questionmark"
        punctenclose="close"> </token>
    </sentence>
    <sentence id="5">
      <token id="t5.1" form="What" lemma="what" tag="WP" ctag="WP" pos="pronoun"
        type="interrogative"> </token>
      <token id="t5.2" form="does" lemma="do" tag="VBZ" ctag="VBZ" pos="verb" vform="personal"
        person="3"> </token>
      <token id="t5.3" form="it" lemma="it" tag="PRP" ctag="PRP" pos="pronoun" type="personal"> </token>
      <token id="t5.4" form="make" lemma="make" tag="VBP" ctag="VBP" pos="verb" vform="personal"> </token>
      <token id="t5.5" form="you" lemma="you" tag="PRP" ctag="PRP" pos="pronoun" type="personal"> </token>
      <token id="t5.6" form="think" lemma="think" tag="VBP" ctag="VBP" pos="verb" vform="personal"> </token>
      <token id="t5.7" form="about" lemma="about" tag="RB" ctag="RB" pos="adverb" type="general"> </token>
      <token id="t5.8" form="?" lemma="?" tag="Fit" ctag="Fit" pos="punctuation" type="questionmark"
        punctenclose="close"> </token>
    </sentence>
    <sentence id="6">
      <token id="t6.1" form="Shakespeare" lemma="shakespeare" tag="NP" ctag="NP" pos="noun"
        type="proper"> </token>
      <token id="t6.2" form="was" lemma="be" tag="VBD" ctag="VBD" pos="verb" vform="past"> </token>
      <token id="t6.3" form="a" lemma="a" tag="DT" ctag="DT" pos="determiner"> </token>
      <token id="t6.4" form="dreamer" lemma="dreamer" tag="NN" ctag="NN" pos="noun" type="common"
        num="singular"> </token>
      <token id="t6.5" form="," lemma="," tag="Fc" ctag="Fc" pos="punctuation" type="comma"> </token>
      <token id="t6.6" form="and" lemma="and" tag="CC" ctag="CC" pos="conjunction"
        type="coordinating"> </token>
      <token id="t6.7" form="some" lemma="some" tag="DT" ctag="DT" pos="determiner"> </token>
      <token id="t6.8" form="say" lemma="say" tag="VBP" ctag="VBP" pos="verb" vform="personal"> </token>
      <token id="t6.9" form="he" lemma="he" tag="PRP" ctag="PRP" pos="pronoun" type="personal"> </token>
      <token id="t6.10" form="was" lemma="be" tag="VBD" ctag="VBD" pos="verb" vform="past"> </token>
      <token id="t6.11" form="a" lemma="a" tag="DT" ctag="DT" pos="determiner"> </token>
      <token id="t6.12" form="philosopher" lemma="philosopher" tag="NN" ctag="NN" pos="noun"
        type="common" num="singular"> </token>
      <token id="t6.13" form="too" lemma="too" tag="RB" ctag="RB" pos="adverb" type="general"> </token>
      <token id="t6.14" form="." lemma="." tag="Fp" ctag="Fp" pos="punctuation" type="period"
      > </token>
    </sentence>
    <sentence id="7">
      <token id="t7.1" form="In" lemma="in" tag="IN" ctag="IN" pos="preposition"> </token>
      <token id="t7.2" form="this" lemma="this" tag="DT" ctag="DT" pos="determiner"> </token>
      <token id="t7.3" form="sentence" lemma="sentence" tag="NN" ctag="NN" pos="noun" type="common"
        num="singular"> </token>
      <token id="t7.4" form="he" lemma="he" tag="PRP" ctag="PRP" pos="pronoun" type="personal"> </token>
      <token id="t7.5" form="tells" lemma="tell" tag="VBZ" ctag="VBZ" pos="verb" vform="personal"
        person="3"> </token>
      <token id="t7.6" form="us" lemma="us" tag="PRP" ctag="PRP" pos="pronoun" type="personal"> </token>
      <token id="t7.7" form="that" lemma="that" tag="IN" ctag="IN" pos="preposition"> </token>
      <token id="t7.8" form="our" lemma="our" tag="PRPos" ctag="PRPos" pos="pronoun"
        type="possessive"> </token>
      <token id="t7.9" form="lives" lemma="life" tag="NNS" ctag="NNS" pos="noun" type="common"
        num="plural"> </token>
      <token id="t7.10" form="are" lemma="be" tag="VBP" ctag="VBP" pos="verb" vform="personal"> </token>
      <token id="t7.11" form="short" lemma="short" tag="JJ" ctag="JJ" pos="adjective"> </token>
      <token id="t7.12" form="but" lemma="but" tag="CC" ctag="CC" pos="conjunction"
        type="coordinating"> </token>
      <token id="t7.13" form="we" lemma="we" tag="PRP" ctag="PRP" pos="pronoun" type="personal"> </token>
      <token id="t7.14" form="can" lemma="can" tag="MD" ctag="MD" pos="verb" type="modal"> </token>
      <token id="t7.15" form="think" lemma="think" tag="VB" ctag="VB" pos="verb" vform="infinitive"> </token>
      <token id="t7.16" form="up" lemma="up" tag="RP" ctag="RP" pos="particle"> </token>
      <token id="t7.17" form="big" lemma="big" tag="JJ" ctag="JJ" pos="adjective"> </token>
      <token id="t7.18" form="and" lemma="and" tag="CC" ctag="CC" pos="conjunction"
        type="coordinating"> </token>
      <token id="t7.19" form="important" lemma="important" tag="JJ" ctag="JJ" pos="adjective"> </token>
      <token id="t7.20" form="ideas" lemma="idea" tag="NNS" ctag="NNS" pos="noun" type="common"
        num="plural"> </token>
      <token id="t7.21" form="in" lemma="in" tag="IN" ctag="IN" pos="preposition"> </token>
      <token id="t7.22" form="that" lemma="that" tag="DT" ctag="DT" pos="determiner"> </token>
      <token id="t7.23" form="short" lemma="short" tag="JJ" ctag="JJ" pos="adjective"> </token>
